In [1]:
!uv sync

Resolved 52 packages in 3ms
Checked 47 packages in 4ms

In [2]:
import pandas as pd

In [3]:
DATA_PATH = 'candidate_public/candidate_data'

In [5]:
articles = pd.read_feather(DATA_PATH + "/articles.f")
articles

/Users/waxyyy99/Code/avito_bootcamp_test/.venv/lib/python3.13/site-packages/pandas/io/feather_format.py:178: FutureWarning: pyarrow.feather.read_table is deprecated as of 24.0.0. Use pyarrow.ipc.open_file() / RecordBatchFileReader instead. Feather V2 is the Arrow IPC file format.
  pa_table = feather.read_table(

,article_id,title,body
0,1730,Имя или название компании,"<ol><li><p>Зайдите в раздел <a href=""https://w..."
1,1746,"Понять, что профиль заблокирован","<p>Проверьте, какое сообщение вы видите при вх..."
2,1747,Не допустить блокировки профиля,<ol><li><p><strong>Не заводите несколько аккау...
3,1774,Оставить или удалить профиль,<p>⚡ Не удаляйте профиль с подтверждёнными дан...
4,1775,Удалить профиль,"<p>⚡ Удалить профиль не получится, если у вас ..."
...,...,...,...
788,4545,Лента постов от продавца,<p>Теперь на Авито можно публиковать не только...
789,4547,Записаться на тест-драйв,<p>Записаться на тест-драйв</p>
790,4548,Автоматический чат с продавцом,"<p>Иногда покупатель интересуется объявлением,..."
791,4549,Автоматический чат с продавцом,"<p>Иногда покупатель интересуется объявлением,..."
792,4551,Неверный параметр в Товарах,<p><strong>Почему отклонили</strong>: Параметр...

In [6]:
calibration = pd.read_feather(DATA_PATH + "/calibration.f")
calibration

/Users/waxyyy99/Code/avito_bootcamp_test/.venv/lib/python3.13/site-packages/pandas/io/feather_format.py:178: FutureWarning: pyarrow.feather.read_table is deprecated as of 24.0.0. Use pyarrow.ipc.open_file() / RecordBatchFileReader instead. Feather V2 is the Arrow IPC file format.
  pa_table = feather.read_table(

     query_id                                         query_text ground_truth
0           1              Как передать товар через службу авито    1909 4234
1           2  Можете подсказать, если заказать товар Авито д...    2865 4400
2           3     Здравствуйте. Как отправить товар через Авито.         1909
3           4  как получить деньги за возрат если продавец уж...    4400 4403
4           5  Когда мне прийдут деньги за доставку, сегодня ...         4361
..        ...                                                ...          ...
495       496  Хочу закрыть кошелек и чтобы деньги за продажи...         4384
496       497             Сколько платит покупатель за доставку?    1951 4234
497       498                   Почему нету доставки за <MONEY>?    1951 4234
498       499  Добрый вечер 🌇 Присылали промокод на <MONEY> н...    2665 4214
499       500          Почему не могу списать бонусы при покупке    2646 4219

[500 rows x 3 columns]